# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Pygments" = super.buildPythonPackage {
    name = "Pygments-2.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/55/55cd82a72af652d71eb14f318e2d12d2fd14ded43d6fd105e50ed395198c/Pygments-2.4.0.tar.gz";
      sha256 = "1xb5n3hvhk63kxypc03k7kfry20pny6gygi4bsl9kw1rnzzsdjri";
    };
  };
  "asn1crypto" = super.buildPythonPackage {
    name = "asn1crypto-0.24.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/f1/8db7daa71f414ddabfa056c4ef792e1461ff655c2ae2928a2b675bfed6b4/asn1crypto-0.24.0.tar.gz";
      sha256 = "0jaf8rf9dx1lf23xfv2cdd5h52f1qr3w8k63985bc35g3d220p4x";
    };
  };
  "astroid" = super.buildPythonPackage {
    name = "astroid-1.6.6";
    doCheck = false;
    propagatedBuildInputs = [
      self."backports.functools-lru-cache"
      self."enum34"
      self."lazy-object-proxy"
      self."singledispatch"
      self."six"
      self."wrapt"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/75/bf/f0af5fcc6deb53b3a480c3487632eeb6324a3ae51cd20161865853f87c31/astroid-1.6.6.tar.gz";
      sha256 = "1ir4n736x36iyg8rq263bwszamlncfh7xz94gpxxkwa4gzy6jn6j";
    };
  };
  "atomicwrites" = super.buildPythonPackage {
    name = "atomicwrites-1.3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/0f/cd484ac8820fed363b374af30049adc8fd13065720fd4f4c6be8a2309da7/atomicwrites-1.3.0.tar.gz";
      sha256 = "19ngcscdf3jsqmpcxn6zl5b6anmsajb6izp1smcd1n02midl9abm";
    };
  };
  "attrs" = super.buildPythonPackage {
    name = "attrs-19.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/d9/931a24cc5394f19383fbbe3e1147a0291276afa43a0dc3ed0d6cd9fda813/attrs-19.1.0.tar.gz";
      sha256 = "16g33zr5f449lqc5wgvzpknxryfzrfsxcr6kpgxwn7l5fkv71f7h";
    };
  };
  "backports.functools-lru-cache" = super.buildPythonPackage {
    name = "backports.functools-lru-cache-1.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/d4/156eb5fbb08d2e85ab0a632e2bebdad355798dece07d4752f66a8d02d1ea/backports.functools_lru_cache-1.5.tar.gz";
      sha256 = "06jgv8gib4fhky0p5cmxdghvsgjyzcdgk48k8pxb1ccf11znk64x";
    };
  };
  "bleach" = super.buildPythonPackage {
    name = "bleach-3.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/5a/0df03e8735cd9c75167528299c738702437589b9c71a849489d00ffa82e8/bleach-3.1.0.tar.gz";
      sha256 = "1yhrgrhkln8bd6gn3imj69g1h4xqah9gaz9q26crqr6gmmvpzprz";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2019.3.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/b8/d1ea38513c22e8c906275d135818fee16ad8495985956a9b7e2bb21942a1/certifi-2019.3.9.tar.gz";
      sha256 = "1bnpw7hrf9i1l9gfxjnzi45hkrvzz0pyn9ia8m4mw7sxhgb08qdj";
    };
  };
  "cffi" = super.buildPythonPackage {
    name = "cffi-1.12.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."pycparser"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz";
      sha256 = "0x075521fxwv0mfp4cqzk7lvmw4n94bjw601qkcv314z5s182704";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "check-manifest" = super.buildPythonPackage {
    name = "check-manifest-0.38";
    doCheck = false;
    propagatedBuildInputs = [
      self."toml"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/c3/99f1dc28ef1b743fd8b53c7fd07bb1502ec658a495b8d2e0f02610d6c2f7/check-manifest-0.38.tar.gz";
      sha256 = "08xkgx4a2jminzg8by15cdndxjhz6ff4r0ghnhzgin3l72g7996v";
    };
  };
  "colorama" = super.buildPythonPackage {
    name = "colorama-0.4.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/53/e785891dce0e2f2b9f4b4ff5bc6062a53332ed28833c7afede841f46a5db/colorama-0.4.1.tar.gz";
      sha256 = "0ba247bx5pc60hcpbf3rjsqk0whilg241i9qdfnlcwij5qgdgvh5";
    };
  };
  "configparser" = super.buildPythonPackage {
    name = "configparser-3.7.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e2/1c/83fd53748d8245cb9a3399f705c251d3fc0ce7df04450aac1cfc49dd6a0f/configparser-3.7.4.tar.gz";
      sha256 = "0xac32886ihs2xg7w1gppcq2sgin5qsm8lqwijs5xifq9w0x0q6s";
    };
  };
  "coverage" = super.buildPythonPackage {
    name = "coverage-4.5.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/82/70/2280b5b29a0352519bb95ab0ef1ea942d40466ca71c53a2085bdeff7b0eb/coverage-4.5.3.tar.gz";
      sha256 = "02f6m073qdispn96rc616hg0rnmw1pgqzw3bgxwiwza4zf9hirlx";
    };
  };
  "coveralls" = super.buildPythonPackage {
    name = "coveralls-1.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."coverage"
      self."docopt"
      self."requests"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/76/5592d2757487de97d64865d9eb586046820ac90681a63137a40bfe20d650/coveralls-1.7.0.tar.gz";
      sha256 = "10gdzyik8fzx9x8y10r0myx0dl01l81bnds8cmpz4w2hn4ipi6zz";
    };
  };
  "cryptography" = super.buildPythonPackage {
    name = "cryptography-2.6.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."asn1crypto"
      self."cffi"
      self."enum34"
      self."ipaddress"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/ca/bc827c5e55918ad223d59d299fff92f3563476c3b00d0a9157d9c0217449/cryptography-2.6.1.tar.gz";
      sha256 = "19iwz5avym5zl6jrrrkym1rdaa9h61j20ph4cswsqgv8xg5j3j16";
    };
  };
  "docopt" = super.buildPythonPackage {
    name = "docopt-0.6.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz";
      sha256 = "14f4hn6d1j4b99svwbaji8n2zj58qicyz19mm0x6pmhb50jsics9";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "enum34" = super.buildPythonPackage {
    name = "enum34-1.1.6";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz";
      sha256 = "1cgm5ng2gcfrkrm3hc22brl6chdmv67b9zvva9sfs7gn7dwc9n4a";
    };
  };
  "eradicate" = super.buildPythonPackage {
    name = "eradicate-1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/ed/5b4506e122114f9439482d2a810ade4aa06cc4e306185931889e58b47f46/eradicate-1.0.tar.gz";
      sha256 = "06nhs8wml5f5k96gbq7jl417bmsqnxy8aykpzbzrvm3gmqmaizag";
    };
  };
  "funcsigs" = super.buildPythonPackage {
    name = "funcsigs-1.0.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/4a/db842e7a0545de1cdb0439bb80e6e42dfe82aaeaadd4072f2263a4fbed23/funcsigs-1.0.2.tar.gz";
      sha256 = "0l4g5818ffyfmfs1a924811azhjj8ax9xd1cffr1mzd3ycn0zfx7";
    };
  };
  "futures" = super.buildPythonPackage {
    name = "futures-3.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/9e/7b2ff7e965fc654592269f2906ade1c7d705f1bf25b7d469fa153f7d19eb/futures-3.2.0.tar.gz";
      sha256 = "0rdjmmsab550kxsssdq49jcniz77zlkpw4pvi9hvib3lsskjmh4y";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz";
      sha256 = "01rlkigdxg17sf9yar1jl8n18ls59367wqh59hnawlyg53vb6my3";
    };
  };
  "ipaddress" = super.buildPythonPackage {
    name = "ipaddress-1.0.22";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/8d/77b8cedcfbf93676148518036c6b1ce7f8e14bf07e95d7fd4ddcb8cc052f/ipaddress-1.0.22.tar.gz";
      sha256 = "0b570bm6xqpjwqis15pvdy6lyvvzfndjvkynilcddjj5x98wfimi";
    };
  };
  "isort" = super.buildPythonPackage {
    name = "isort-4.3.18";
    doCheck = false;
    propagatedBuildInputs = [
      self."backports.functools-lru-cache"
      self."futures"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/3e/22308cdac59f5ef0e8157a33a01eb611e7a3a93e9711ed88ffc9a5b73ba0/isort-4.3.18.tar.gz";
      sha256 = "0w0qgmxszrrjxs0szz5w9qac7lpkignssdg6mf95akhixgv136gh";
    };
  };
  "lazy-object-proxy" = super.buildPythonPackage {
    name = "lazy-object-proxy-1.4.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/57/a36f682668ffc453e86ddfb5a2a49848edcb7bd04a210a5a8692a48ed9c4/lazy-object-proxy-1.4.1.tar.gz";
      sha256 = "0wbsaaj2dgsx187imwyqs7xbigbxnh3shkqapiw996ydi5h3z9sb";
    };
  };
  "mccabe" = super.buildPythonPackage {
    name = "mccabe-0.6.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/18/fa675aa501e11d6d6ca0ae73a101b2f3571a565e0f7d38e062eec18a91ee/mccabe-0.6.1.tar.gz";
      sha256 = "07w3p1qm44hgxf3vvwz84kswpsx6s7kvaibzrsx5dzm0hli1i3fx";
    };
  };
  "more-itertools" = super.buildPythonPackage {
    name = "more-itertools-5.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/26/30fc0d541d9fdf55faf5ba4b0fd68f81d5bd2447579224820ad525934178/more-itertools-5.0.0.tar.gz";
      sha256 = "1r12cm6mcdwdzz7d47a6g4l437xsvapdlgyhqay3i2nrlv03da9q";
    };
  };
  "pathlib2" = super.buildPythonPackage {
    name = "pathlib2-2.3.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."scandir"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/d7/a2568f4596b75d2c6e2b4094a7e64f620decc7887f69a1f2811931ea15b9/pathlib2-2.3.3.tar.gz";
      sha256 = "0hpp92vqqgcd8h92msm9slv161b1q160igjwnkf2ag6cx0c96695";
    };
  };
  "pkginfo" = super.buildPythonPackage {
    name = "pkginfo-1.5.0.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/04/fd6683d24581894be8b25bc8c68ac7a0a73bf0c4d74b888ac5fe9a28e77f/pkginfo-1.5.0.1.tar.gz";
      sha256 = "1fs825s0vrylg45rj16nm0vmnhvpbc233gsb8banq60wa74g493l";
    };
  };
  "pluggy" = super.buildPythonPackage {
    name = "pluggy-0.11.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/a1/862ab336e8128fde20981d2c1aa8506693412daf5083b1911d539412676b/pluggy-0.11.0.tar.gz";
      sha256 = "10511a54dvafw1jrk75mrhml53c7b7w4yaw7241696lc2hfvr895";
    };
  };
  "py" = super.buildPythonPackage {
    name = "py-1.8.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/5a/87ca5909f400a2de1561f1648883af74345fe96349f34f737cdfc94eba8c/py-1.8.0.tar.gz";
      sha256 = "0lsy1gajva083pzc7csj1cvbmminb7b4l6a0prdzyb3fd829nqyw";
    };
  };
  "pycodestyle" = super.buildPythonPackage {
    name = "pycodestyle-2.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/d1/41294da5915f4cae7f4b388cea6c2cd0d6cd53039788635f6875dfe8c72f/pycodestyle-2.5.0.tar.gz";
      sha256 = "0v4prb05n21bm8650v0a01k1nyqjdmkrsm3zycfxh2j5k9n962p4";
    };
  };
  "pycparser" = super.buildPythonPackage {
    name = "pycparser-2.19";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz";
      sha256 = "1cr5dcj9628lkz1qlwq3fv97c25363qppkmcayqvd05dpy573259";
    };
  };
  "pydocstyle" = super.buildPythonPackage {
    name = "pydocstyle-3.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."configparser"
      self."six"
      self."snowballstemmer"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/e6/a0669df17a97e462915a10a7d6c567658b60eceddebf62a3fb9975c00196/pydocstyle-3.0.0.tar.gz";
      sha256 = "1m1xv9clkg9lgzyza6dnj359z04vh5g0h49nhzghv7lg81gchhap";
    };
  };
  "pyflakes" = super.buildPythonPackage {
    name = "pyflakes-2.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/64/87303747635c2988fcaef18af54bfdec925b6ea3b80bcd28aaca5ba41c9e/pyflakes-2.1.1.tar.gz";
      sha256 = "18pq95a1xj2dgdd0m85gyfsn40jajj4xc3lp8wfv7igqhrc86xnr";
    };
  };
  "pylama" = super.buildPythonPackage {
    name = "pylama-7.7.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."mccabe"
      self."pycodestyle"
      self."pydocstyle"
      self."pyflakes"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/89/082aa9378e382bd8132c3a8a3ef09af71e1c8f5c00cef211583e476ba4df/pylama-7.7.1.tar.gz";
      sha256 = "13vx7daqz2918y9s8q3v2i3xaq3ah43a9p58srqi6hqskkpm7blv";
    };
  };
  "pylint" = super.buildPythonPackage {
    name = "pylint-1.9.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."astroid"
      self."backports.functools-lru-cache"
      self."configparser"
      self."isort"
      self."mccabe"
      self."singledispatch"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8f/0b/a2e834d291afeb5a14512eba898d12a39775c05440cc12fb8a4138d311e7/pylint-1.9.4.tar.gz";
      sha256 = "14ysa4jg1lz5hmaw57qk5qbyz48nn30y29gsva6vbic7ambqa7pf";
    };
  };
  "pyopenssl" = super.buildPythonPackage {
    name = "pyopenssl-19.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."cryptography"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/40/d0/8efd61531f338a89b4efa48fcf1972d870d2b67a7aea9dcf70783c8464dc/pyOpenSSL-19.0.0.tar.gz";
      sha256 = "007j40y7x3k8xj54dy2qnij9lldfp71k9mkflhd9vqbdiwrndjmf";
    };
  };
  "pyroma" = super.buildPythonPackage {
    name = "pyroma-2.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/e4/540694eb7116c1557244f3d5c656673cea48674cb40759a78bf7bbc14c47/pyroma-2.4.tar.gz";
      sha256 = "0zzfnrrpydj44d5bg47fqhbg4mi5j23v9j3ssfdzyswpfyq1r8cl";
    };
  };
  "pytest" = super.buildPythonPackage {
    name = "pytest-4.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."atomicwrites"
      self."attrs"
      self."funcsigs"
      self."more-itertools"
      self."pathlib2"
      self."pluggy"
      self."py"
      self."setuptools"
      self."six"
      self."wcwidth"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/04/f2ae104dffcd6b2e3c7ed35773b760971c1bacbe4447250966f927cf5efd/pytest-4.5.0.tar.gz";
      sha256 = "090bf215hp3dbrqx43bq73m8dz6r630kl7s4qld4b3wgjpxa92hs";
    };
  };
  "pytest-runner" = super.buildPythonPackage {
    name = "pytest-runner-4.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/0a/1e73c3a3d3f4f5faf5eacac4e55675c1627b15d84265b80b8fef3f8a3fb5/pytest-runner-4.4.tar.gz";
      sha256 = "1x0d9n40lsiphblbs61rdc0d5r31f6vh0vcahqdv0mffakbnrb80";
    };
  };
  "readme-renderer" = super.buildPythonPackage {
    name = "readme-renderer-24.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."Pygments"
      self."bleach"
      self."docutils"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/de/a567140b13a0fc8d3b04d85a510b5a7d9869b44b2939fa8ac07c5e421485/readme_renderer-24.0.tar.gz";
      sha256 = "0br0562lnvj339f1nwz4nfl4ay49rw05xkqacigzf9wz4mdza5mv";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.21.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz";
      sha256 = "13jr0wkj9c2j8c0c8iaal9iivi0bpxghnsdn6lxcpnmc657q4ajh";
    };
  };
  "requests-toolbelt" = super.buildPythonPackage {
    name = "requests-toolbelt-0.9.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/28/30/7bf7e5071081f761766d46820e52f4b16c8a08fef02d2eb4682ca7534310/requests-toolbelt-0.9.1.tar.gz";
      sha256 = "1h3gm88dcjbd7gm229a7x5qkkhnsqsjz0m0l2xyavm2ab3a8k04n";
    };
  };
  "scandir" = super.buildPythonPackage {
    name = "scandir-1.10.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz";
      sha256 = "1bkqwmf056pkchf05ywbnf659wqlp6lljcdb0y88wr9f0vv32ijd";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-41.0.1";
    doCheck = false;
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/64/a18a487b4391a05b9c7f938b94a16d80305bf0369c6b0b9509e86165e1d3/setuptools-41.0.1.zip";
      sha256 = "04sns22y2hhsrwfy1mha2lgslvpjsjsz8xws7h2rh5a7ylkd28m2";
    };
  };
  "setuptools-scm" = super.buildPythonPackage {
    name = "setuptools-scm-3.3.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/44/53cad68ce686585d12222e6769682c4bdb9686808d2739671f9175e2938b/setuptools_scm-3.3.3.tar.gz";
      sha256 = "19cyndx23xmpbhz4qrwmfwsmnnaczd0dw7qg977ksq2dbvxy29dx";
    };
  };
  "singledispatch" = super.buildPythonPackage {
    name = "singledispatch-3.4.0.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/e9/513ad8dc17210db12cb14f2d4d190d618fb87dd38814203ea71c87ba5b68/singledispatch-3.4.0.3.tar.gz";
      sha256 = "171b7ip0hsq5qm83np40h3phlr36ym18w0lay0a8v08kvy3sy1jv";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.12.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz";
      sha256 = "0wxs1q74v07ssjywbbm7x6h5v9qx209ld2yfsif4060sxi0h2sni";
    };
  };
  "snowballstemmer" = super.buildPythonPackage {
    name = "snowballstemmer-1.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz";
      sha256 = "0a0idq4y5frv7qsg2x62jd7rd272749xk4x99misf5rcifk2d7wi";
    };
  };
  "toml" = super.buildPythonPackage {
    name = "toml-0.10.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/19/5cbd78eac8b1783671c40e34bb0fa83133a06d340a38b55c645076d40094/toml-0.10.0.tar.gz";
      sha256 = "0p1xww2mzkhqvxkfvmfzm58bbfj812zhdz4rwdjiv94ifz2q37r2";
    };
  };
  "tqdm" = super.buildPythonPackage {
    name = "tqdm-4.31.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/9b/f3036a9a11c250eb51d38acf94d1d7c33a0d4da8a8931bfdf15e12d505b1/tqdm-4.31.1.tar.gz";
      sha256 = "01fdks20qx09xw3zdxda6ybiqlycjy8zppgnc8izfqg9xgipfag2";
    };
  };
  "twine" = super.buildPythonPackage {
    name = "twine-1.13.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pkginfo"
      self."readme-renderer"
      self."requests"
      self."requests-toolbelt"
      self."setuptools"
      self."tqdm"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/af/4f5bfaa8e9c0ddce229b058a4ebdc11a6e05e9c2e51b854d1d0e8f764d09/twine-1.13.0.tar.gz";
      sha256 = "1p0lbgzz14i00g7a9x8rw5q5fpbwz2hkm8cz3ndlxiyg7s9rrhnn";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.24.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/53/37d82ab391393565f2f831b8eedbffd57db5a718216f82f1a8b4d381a1c1/urllib3-1.24.1.tar.gz";
      sha256 = "08lwd9f3hqznyf32vnzwvp87pchx062nkbgyrf67rwlkgj0jk5fy";
    };
  };
  "wcwidth" = super.buildPythonPackage {
    name = "wcwidth-0.1.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz";
      sha256 = "0pn6dflzm609m4r3i8ik5ni9ijjbb5fa3vg1n7hn6vkd49r77wrx";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "wheel" = super.buildPythonPackage {
    name = "wheel-0.33.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/b0/f478e80aeace42fe251225a86752799174a94314c4a80ebfc5bf0ab1153a/wheel-0.33.4.tar.gz";
      sha256 = "0r95020hjslzvmqd9973p55zzgz4j2qhgg6c74jp4nsvsh1zmz32";
    };
  };
  "wrapt" = super.buildPythonPackage {
    name = "wrapt-1.11.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/b2/0f71ca90b0ade7fad27e3d20327c996c6252a2ffe88f50a95bba7434eda9/wrapt-1.11.1.tar.gz";
      sha256 = "0cqmysny1pz01jw26q48q5zasvns6507rwhgm6wcw743f0r01sja";
    };
  };
  "zest.releaser" = super.buildPythonPackage {
    name = "zest.releaser-6.18.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."colorama"
      self."requests"
      self."setuptools"
      self."six"
      self."twine"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/4a/0d9f3eac02cda49fff11d583ed4f0a943751e3270c6ebf1f9c1a14abcac5/zest.releaser-6.18.2.tar.gz";
      sha256 = "1p0b96dfwbyrlvvn9p3v7vfx7mgsl93sarjwg5hrkf9ml7cm6y0j";
    };
  };
}
